allsubj = {
    'coad'	01	'columbini_A'
    'coad'	02	'columbini_A'
    'coad'	03	'columbini_A'
    'coad'	04	'columbini_A'
    'saco'	01	'columbini_S'
    'saco'	02	'columbini_S'
    'saco'	03	'columbini_S'
    'saco'	04	'columbini_S'
    'sege'	01	'geus'
    'sege'	02	'geus'
    'sege'	03	'geus'
    'sege'	04	'geus'
    'maju'	01	'massin'
    'maju'	02	'massin'
    'maju'	03	'massin'
    'maju'	04	'massin'
    'mini'	01	'minisini'
    'mini'	02	'minisini'
    'mini'	03	'minisini'
    'mini'	04	'minisini'
    'knar'	01	'knar'
    'knar'	02	'knar'
    'knar'	03	'knar'
    'knar'	04	'knar'
    'Jerome'	01	'jerome'
    'Jerome'	02	'jerome'
    'Jerome'	03	'jerome'
    'Jerome'	04	'jerome'
    'jemi'	01	'mixhe'
    'jemi'	02	'mixhe'
    'jemi'	03	'mixhe'
    'jemi'	04	'mixhe'
    'milou'	01	'miloudi'
    'milou'	02	'miloudi'
    'milou'	03	'miloudi'
    'milou'	04	'miloudi'
    'mami'	01	'marchandise'
    'mami'	02	'marchandise'
    'mami'	03	'marchandise'
    'mami'	04	'marchandise'
    };

dcmlist = {
    'coad_01'
    'coad_03'
    'saco_01'
    'saco_03'
    'sege_01'
    'sege_03'
    'maju_01'
    'maju_03'
    'mini_01'
    'mini_03'
    'knar_01'
    'knar_03'
    'jerome_01'
    'jerome_03'
    'jemi_01'
    'jemi_03'
    'milou_01'
    'milou_03'
    'mami_01'
    'mami_03'
    };

anes = {
    'coad'
    'saco'
    'sege'
%     'maju'
%     'mini'
%     'knar'
%     'jerome'
%     'jemi'
%     'milou'
%     'mami'
        };
